### ISSUE TITLE
[already fixed in the development branch] Giveaway - Start image filename indexes at 1 instead of 0

### ISSUE THREAD

**Issue by tannerhallman** [juliancwirko/elven-nft-minter-sc#19]
I don't think it's intuitive that you need to have image names starting at number 0 (instead of 1).

0.png <--
1.png

I would expect that it would start at 1. Not sure if this was a change that was introduced in the new shuffle mechanism or what!

Example tx: https://devnet-explorer.elrond.com/nfts/NTLPRK-c73cc4-01

**Comment by tannerhallman** [comment]
After minting another collection, I noticed that it selected image 10.jpg which means with a total collection size of 10, it selects images between 0-10 which means 11 shuffle options.

0
https://devnet-explorer.elrond.com/nfts/NTLPRK-10beda-01

10
https://devnet-explorer.elrond.com/nfts/NTLPRK-10beda-03

**Comment by juliancwirko** [comment]
Hey, thanks for reporting. Yes, it shouldn't happen. It is a bug. You will still have the ten items, but one index will be missing.

Could you tell me more about it?

1. What smart contract was used: modified, from the main branch or maybe from the development branch?
2. What was the configuration when deploying it?

Thanks!

**Comment by juliancwirko** [comment]
I think I fixed it on the development branch. I will do more tests later. 

The problem was that there wasn't a shuffle 'gatekeeper' for the `giveaway` endpoint. The shuffle must be called at least once before minting (also giveaway). It should be done by hand because I can't run it in the init function. I could probably automate it in the CLI the same as with `populateIndexes`, but without the CLI, you will still need to remember about `populateIndexes` and `shuffle`.

Please try the wasm file from the development branch, and thanks for reporting, good catch :)

**Comment by tannerhallman** [comment]
Hey sorry for the delay. Bad at GitHub notifications but it seems like you were able to resolve this! Thanks for your work.
